Modify Travis configuration to use stack
Modify ".travis.yml" to use "stack" to build the package.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,46 +1,91 @@
+language: c
+
+os: linux
+
+cache:
+  directories:
+    - $HOME/.stack
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
 env:
-  - GHCVER=7.6.3
-  - GHCVER=7.8.3
+  jobs:
+    - EXEC="stack" RESOLVER="lts-14"
 
 before_install:
-  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-  - travis_retry sudo apt-get update
-  - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy
-  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+  - mkdir -p ~/.local/bin
+  - export PATH="$HOME/.local/bin:$PATH"
+  - |
+      travis-retry curl \
+      -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
+      tar xz --wildcards --strip-components=1 -C ~/.local/biin '*/stack'
 
 install:
-  - cabal-1.20 update
-  - travis_retry sudo apt-get -q -y install hlint || cabal-1.20 install hlint
-  - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks
+  - export STACK="stack --resolver=$RESOLVER"
+  - ${STACK} --version
+  - ${STACK} test --no-terminal --install-ghc --only-dependencies
 
 script:
-  - hlint . --ignore="Parse error"
-  - cabal-1.20 configure --enable-tests --enable-benchmarks --enable-library-coverage -v2
-  - cabal-1.20 build
-  - |
-    if [ $GHCVER = "7.8.3" ]; then
-      cabal-1.20 test --show-details=always
-    else
-      dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.20 --show-details=always
-    fi
-  - cabal-1.20 check
-  - cabal-1.20 sdist
-  - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
-    (cd dist/;
-    if [ -f "$SRC_TGZ" ]; then
-      cabal-1.20 install "$SRC_TGZ";
-    else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
-    fi)
+  - echo stack=$STACK
+  - $STACK --no-terminal build --fast --test --coverage codecov-haskell
 
 after_script:
-  - dist/build/codecov-haskell/codecov-haskell test-all --exclude-dir=test --display-report --print-response
+  - echo stack=$STACK
+  - STACK_TIX=$($STACK path --local-hpc-root)/codecov-haskell/test-all/test-all.tix
+  - STACK_CABAL_VER=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/hpc
+  - STACK_MIX_DIR=$STACK_CABAL_VER
+  - |
+    stack exec -- codecov-haskell \
+      --tix-dir=$STACK_TIX \
+      --mix-dir=$STACK_CABAL_VER
+      --display-report
+      test-all
 
-notifications:
-  webhooks:
-  urls:
-    - https://webhooks.gitter.im/e/3ff64a7879ffa1a444b6
-  on_success: change
-  on_failure: always
-  on_start: false
+# env:
+#   - GHCVER=7.6.3
+#   - GHCVER=7.8.3
+
+# before_install:
+#   - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+#   - travis_retry sudo apt-get update
+#   - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy
+#   - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
+# install:
+#   - cabal-1.20 update
+#   - travis_retry sudo apt-get -q -y install hlint || cabal-1.20 install hlint
+#   - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks
+
+# script:
+#   - hlint . --ignore="Parse error"
+#   - cabal-1.20 configure --enable-tests --enable-benchmarks --enable-library-coverage -v2
+#   - cabal-1.20 build
+#   - |
+#     if [ $GHCVER = "7.8.3" ]; then
+#       cabal-1.20 test --show-details=always
+#     else
+#       dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.20 --show-details=always
+#     fi
+#   - cabal-1.20 check
+#   - cabal-1.20 sdist
+#   - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
+#     (cd dist/;
+#     if [ -f "$SRC_TGZ" ]; then
+#       cabal-1.20 install "$SRC_TGZ";
+#     else
+#       echo "expected '$SRC_TGZ' not found";
+#       exit 1;
+#     fi)
+
+# after_script:
+#   - dist/build/codecov-haskell/codecov-haskell test-all
+# --exclude-dir=test --display-report --print-response
+
+
+# notifications:
+#   webhooks:
+#   urls:
+#     - https://webhooks.gitter.im/e/3ff64a7879ffa1a444b6
+#   on_success: change
+#   on_failure: always
+#   on_start: false
